# Generated by Django 5.2.3 on 2025-06-11 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Base de Datos')),
                ('file', models.FileField(upload_to='datasources/', verbose_name='Archivo de Datos')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Columnas Detectadas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Plantilla')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Archivo de Plantilla')),
                ('placeholders', models.JSONField(blank=True, null=True, verbose_name='Campos Detectados')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MappingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_generator.datasource', verbose_name='Base de Datos Usada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_generator.documenttemplate', verbose_name='Plantilla Usada')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_placeholder', models.CharField(max_length=255, verbose_name='Campo en Plantilla')),
                ('data_header', models.CharField(max_length=255, verbose_name='Columna en Datos')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='contract_generator.mappingproject')),
            ],
        ),
    ]
